### ISSUE TITLE
Generate longer class names in CSS

### ISSUE THREAD

**Issue by aalin** [mayu-live/framework#22]
According to [this comment on StackOverflow](https://stackoverflow.com/a/6732899), class names can contain almost anything...

This means that, right now, class names look like this:

`.title-THPvbm_kJn5Ytiqx`

Those names aren't very readable...

It would be better to generate:

```html
<h1 class="app/components/MyComponent.css#title-THPvbm_kJn5Ytiqx">title</h1>
```

```css
.app\/components\/MyComponent\.css\#title-THPvbm_kJn5Ytiqx {
  background: #f0f;
}
```
