### ISSUE TITLE
Load dependencies in CSS files

### ISSUE THREAD

**Issue by aalin** [mayu-live/framework#59]
The CSS transformer will take:

```css
foo { background-image: url("foobar.png"); }
```
and turn it into:
```css
.demo_foo\?uc88-KVY { background-image: url("LMXcDq"); }
```
and also return this dependencies-array:
```ruby
[
  {
    type: "url",
    url: "foobar.png",
    placeholder: "LMXcDq",
    loc: {
      filePath: "demo.rb",
      start: {
        line: 3,
        column: 25
      },
      end: {
        line: 3,
        column: 34
      }
    }
  }
]
```

So, somehow images need to be loaded and the placeholders should be replaced with their paths
